// Mocks generated by Mockito 5.4.6 from annotations
// in crypto_watch/test/features/price_list/presentation/widgets/price_list_item_favorites_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:crypto_watch/core/storage/local_storage.dart' as _i11;
import 'package:crypto_watch/features/favorites/domain/usecases/add_favorite.dart'
    as _i3;
import 'package:crypto_watch/features/favorites/domain/usecases/get_favorites.dart'
    as _i2;
import 'package:crypto_watch/features/favorites/domain/usecases/remove_favorite.dart'
    as _i4;
import 'package:crypto_watch/features/favorites/domain/usecases/reorder_favorites.dart'
    as _i5;
import 'package:crypto_watch/features/favorites/presentation/bloc/favorites_bloc.dart'
    as _i7;
import 'package:crypto_watch/features/favorites/presentation/bloc/favorites_event.dart'
    as _i9;
import 'package:crypto_watch/features/favorites/presentation/bloc/favorites_state.dart'
    as _i6;
import 'package:flutter_bloc/flutter_bloc.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetFavorites_0 extends _i1.SmartFake implements _i2.GetFavorites {
  _FakeGetFavorites_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddFavorite_1 extends _i1.SmartFake implements _i3.AddFavorite {
  _FakeAddFavorite_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveFavorite_2 extends _i1.SmartFake
    implements _i4.RemoveFavorite {
  _FakeRemoveFavorite_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReorderFavorites_3 extends _i1.SmartFake
    implements _i5.ReorderFavorites {
  _FakeReorderFavorites_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFavoritesState_4 extends _i1.SmartFake
    implements _i6.FavoritesState {
  _FakeFavoritesState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FavoritesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesBloc extends _i1.Mock implements _i7.FavoritesBloc {
  MockFavoritesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetFavorites get getFavorites =>
      (super.noSuchMethod(
            Invocation.getter(#getFavorites),
            returnValue: _FakeGetFavorites_0(
              this,
              Invocation.getter(#getFavorites),
            ),
          )
          as _i2.GetFavorites);

  @override
  _i3.AddFavorite get addFavorite =>
      (super.noSuchMethod(
            Invocation.getter(#addFavorite),
            returnValue: _FakeAddFavorite_1(
              this,
              Invocation.getter(#addFavorite),
            ),
          )
          as _i3.AddFavorite);

  @override
  _i4.RemoveFavorite get removeFavorite =>
      (super.noSuchMethod(
            Invocation.getter(#removeFavorite),
            returnValue: _FakeRemoveFavorite_2(
              this,
              Invocation.getter(#removeFavorite),
            ),
          )
          as _i4.RemoveFavorite);

  @override
  _i5.ReorderFavorites get reorderFavorites =>
      (super.noSuchMethod(
            Invocation.getter(#reorderFavorites),
            returnValue: _FakeReorderFavorites_3(
              this,
              Invocation.getter(#reorderFavorites),
            ),
          )
          as _i5.ReorderFavorites);

  @override
  _i6.FavoritesState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeFavoritesState_4(this, Invocation.getter(#state)),
          )
          as _i6.FavoritesState);

  @override
  _i8.Stream<_i6.FavoritesState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i6.FavoritesState>.empty(),
          )
          as _i8.Stream<_i6.FavoritesState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i9.FavoritesEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i9.FavoritesEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i6.FavoritesState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i9.FavoritesEvent>(
    _i10.EventHandler<E, _i6.FavoritesState>? handler, {
    _i10.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i10.Transition<_i9.FavoritesEvent, _i6.FavoritesState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onChange(_i10.Change<_i6.FavoritesState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [LocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorage extends _i1.Mock implements _i11.LocalStorage {
  MockLocalStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String?> getString(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int?> getInt(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getInt, [key]),
            returnValue: _i8.Future<int?>.value(),
          )
          as _i8.Future<int?>);

  @override
  _i8.Future<void> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool?> getBool(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key]),
            returnValue: _i8.Future<bool?>.value(),
          )
          as _i8.Future<bool?>);

  @override
  _i8.Future<void> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<double?> getDouble(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getDouble, [key]),
            returnValue: _i8.Future<double?>.value(),
          )
          as _i8.Future<double?>);

  @override
  _i8.Future<void> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<String>?> getStringList(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getStringList, [key]),
            returnValue: _i8.Future<List<String>?>.value(),
          )
          as _i8.Future<List<String>?>);

  @override
  _i8.Future<void> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>?> getJson(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getJson, [key]),
            returnValue: _i8.Future<Map<String, dynamic>?>.value(),
          )
          as _i8.Future<Map<String, dynamic>?>);

  @override
  _i8.Future<void> setJson(String? key, Map<String, dynamic>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setJson, [key, value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}
