AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Crypto Watch Backend - Serverless API for cryptocurrency price data

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment environment
  
  ExternalApiUrl:
    Type: String
    Default: https://api.coingecko.com/api/v3
    Description: External cryptocurrency API URL
  
  ExternalApiKey:
    Type: String
    Default: ''
    NoEcho: true
    Description: API key for external service (if required)
  
  SupportedSymbols:
    Type: String
    Default: BTC,ETH,ADA,BNB,XRP,SOL,DOT,DOGE,AVAX,MATIC,LINK,UNI,LTC,ATOM,XLM,ALGO,VET,ICP,FIL,TRX
    Description: Comma-separated list of supported cryptocurrency symbols
  
  RateLimitPerMinute:
    Type: Number
    Default: 100
    Description: Maximum API requests per minute per API key
  
  CacheTTLSeconds:
    Type: Number
    Default: 300
    Description: Cache time-to-live in seconds (5 minutes)

Globals:
  Function:
    Runtime: python3.11
    Timeout: 25
    MemorySize: 512
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref CryptoWatchTable
        ENVIRONMENT: !Ref Environment
        POWERTOOLS_SERVICE_NAME: crypto-watch
        LOG_LEVEL: !If [IsProduction, ERROR, INFO]
    Layers:
      - !Ref SharedLayer

Conditions:
  IsProduction: !Equals [!Ref Environment, prod]
  IsDevelopment: !Equals [!Ref Environment, dev]

Resources:
  # Shared Lambda Layer
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub crypto-watch-shared-${Environment}
      Description: Shared utilities for Crypto Watch backend
      ContentUri: src/shared/
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11

  # DynamoDB Table
  CryptoWatchTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub crypto-watch-data-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [IsProduction, true, false]
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: crypto-watch

  # API Lambda Function
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub crypto-watch-api-${Environment}
      CodeUri: src/api/
      Handler: handler.lambda_handler
      Description: Handles API requests for cryptocurrency prices
      Environment:
        Variables:
          RATE_LIMIT_PER_MINUTE: !Ref RateLimitPerMinute
          CACHE_TTL_SECONDS: !Ref CacheTTLSeconds
      AutoPublishAlias: live
      DeploymentPreference:
        Type: !If [IsProduction, Linear10PercentEvery1Minute, AllAtOnce]
        Alarms: !If
          - IsProduction
          - - !Ref LambdaErrorAlarm
            - !Ref ApiGateway5xxAlarm
            - !Ref LambdaThrottleAlarm
          - !Ref AWS::NoValue
      Events:
        GetPrices:
          Type: Api
          Properties:
            Path: /prices
            Method: get
            RestApiId: !Ref ApiGateway
        GetPriceBySymbol:
          Type: Api
          Properties:
            Path: /prices/{symbol}
            Method: get
            RestApiId: !Ref ApiGateway
        HealthCheck:
          Type: Api
          Properties:
            Path: /health
            Method: get
            RestApiId: !Ref ApiGateway
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CryptoWatchTable
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
              Resource: !GetAtt CryptoWatchTable.Arn
              Condition:
                ForAllValues:StringLike:
                  dynamodb:LeadingKeys:
                    - APIKEY#*
      Tags:
        Environment: !Ref Environment

  # Price Update Lambda Function
  PriceUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub crypto-watch-update-${Environment}
      CodeUri: src/update/
      Handler: handler.lambda_handler
      Description: Fetches and updates cryptocurrency prices from external API
      Timeout: 60
      Environment:
        Variables:
          EXTERNAL_API_URL: !Ref ExternalApiUrl
          EXTERNAL_API_KEY: !Ref ExternalApiKey
          SUPPORTED_SYMBOLS: !Ref SupportedSymbols
      Events:
        ScheduledUpdate:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Description: Update cryptocurrency prices every 5 minutes
            Enabled: true
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CryptoWatchTable
      Tags:
        Environment: !Ref Environment

  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub crypto-watch-api-${Environment}
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET, OPTIONS'"
        AllowHeaders: "'Content-Type,X-Api-Key,Accept-Encoding'"
        AllowOrigin: "'*'"
      GatewayResponses:
        UNAUTHORIZED:
          StatusCode: 401
          ResponseTemplates:
            application/json: '{"error": "Unauthorized", "code": "UNAUTHORIZED"}'
        THROTTLED:
          StatusCode: 429
          ResponseTemplates:
            application/json: '{"error": "Rate limit exceeded", "code": "RATE_LIMIT_EXCEEDED"}'
      Tags:
        Environment: !Ref Environment

  # CloudWatch Log Groups
  ApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/crypto-watch-api-${Environment}
      RetentionInDays: !If [IsProduction, 90, !If [IsDevelopment, 30, 60]]

  UpdateLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/crypto-watch-update-${Environment}
      RetentionInDays: !If [IsProduction, 90, !If [IsDevelopment, 30, 60]]

  # CloudWatch Alarms (Production only)
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProduction
    Properties:
      AlarmName: !Sub crypto-watch-api-errors-${Environment}
      AlarmDescription: Lambda error rate exceeds threshold
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ApiFunction
      TreatMissingData: notBreaching

  ApiGateway5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProduction
    Properties:
      AlarmName: !Sub crypto-watch-api-5xx-${Environment}
      AlarmDescription: API Gateway 5xx error rate exceeds threshold
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 0.1
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub crypto-watch-api-${Environment}
      TreatMissingData: notBreaching

  LambdaThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProduction
    Properties:
      AlarmName: !Sub crypto-watch-api-throttles-${Environment}
      AlarmDescription: Lambda throttle count exceeds threshold
      MetricName: Throttles
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ApiFunction
      TreatMissingData: notBreaching

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/
    Export:
      Name: !Sub crypto-watch-api-endpoint-${Environment}

  ApiFunctionArn:
    Description: API Lambda Function ARN
    Value: !GetAtt ApiFunction.Arn
    Export:
      Name: !Sub crypto-watch-api-function-arn-${Environment}

  UpdateFunctionArn:
    Description: Price Update Lambda Function ARN
    Value: !GetAtt PriceUpdateFunction.Arn
    Export:
      Name: !Sub crypto-watch-update-function-arn-${Environment}

  DynamoDBTableName:
    Description: DynamoDB Table Name
    Value: !Ref CryptoWatchTable
    Export:
      Name: !Sub crypto-watch-table-name-${Environment}
