// Mocks generated by Mockito 5.4.6 from annotations
// in crypto_watch/test/features/price_list/presentation/bloc/price_list_reorder_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:crypto_watch/core/error/failures.dart' as _i7;
import 'package:crypto_watch/core/storage/local_storage.dart' as _i14;
import 'package:crypto_watch/features/favorites/domain/entities/favorite.dart'
    as _i11;
import 'package:crypto_watch/features/favorites/domain/repositories/favorites_repository.dart'
    as _i4;
import 'package:crypto_watch/features/favorites/domain/usecases/add_favorite.dart'
    as _i12;
import 'package:crypto_watch/features/favorites/domain/usecases/get_favorites.dart'
    as _i10;
import 'package:crypto_watch/features/favorites/domain/usecases/remove_favorite.dart'
    as _i13;
import 'package:crypto_watch/features/price_list/domain/entities/crypto_price.dart'
    as _i8;
import 'package:crypto_watch/features/price_list/domain/repositories/price_repository.dart'
    as _i2;
import 'package:crypto_watch/features/price_list/domain/usecases/get_prices.dart'
    as _i5;
import 'package:crypto_watch/features/price_list/domain/usecases/refresh_prices.dart'
    as _i9;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePriceRepository_0 extends _i1.SmartFake
    implements _i2.PriceRepository {
  _FakePriceRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFavoritesRepository_2 extends _i1.SmartFake
    implements _i4.FavoritesRepository {
  _FakeFavoritesRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetPrices].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPrices extends _i1.Mock implements _i5.GetPrices {
  MockGetPrices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PriceRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePriceRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PriceRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i8.CryptoPrice>>> call(
    List<String>? symbols,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [symbols]),
            returnValue:
                _i6.Future<
                  _i3.Either<_i7.Failure, List<_i8.CryptoPrice>>
                >.value(
                  _FakeEither_1<_i7.Failure, List<_i8.CryptoPrice>>(
                    this,
                    Invocation.method(#call, [symbols]),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, List<_i8.CryptoPrice>>>);
}

/// A class which mocks [RefreshPrices].
///
/// See the documentation for Mockito's code generation for more information.
class MockRefreshPrices extends _i1.Mock implements _i9.RefreshPrices {
  MockRefreshPrices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PriceRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePriceRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PriceRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i8.CryptoPrice>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i6.Future<
                  _i3.Either<_i7.Failure, List<_i8.CryptoPrice>>
                >.value(
                  _FakeEither_1<_i7.Failure, List<_i8.CryptoPrice>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, List<_i8.CryptoPrice>>>);
}

/// A class which mocks [GetFavorites].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFavorites extends _i1.Mock implements _i10.GetFavorites {
  MockGetFavorites() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.FavoritesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFavoritesRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.FavoritesRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i11.Favorite>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i6.Future<_i3.Either<_i7.Failure, List<_i11.Favorite>>>.value(
                  _FakeEither_1<_i7.Failure, List<_i11.Favorite>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, List<_i11.Favorite>>>);
}

/// A class which mocks [AddFavorite].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddFavorite extends _i1.Mock implements _i12.AddFavorite {
  MockAddFavorite() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.FavoritesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFavoritesRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.FavoritesRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, void>> call(String? symbol) =>
      (super.noSuchMethod(
            Invocation.method(#call, [symbol]),
            returnValue: _i6.Future<_i3.Either<_i7.Failure, void>>.value(
              _FakeEither_1<_i7.Failure, void>(
                this,
                Invocation.method(#call, [symbol]),
              ),
            ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, void>>);
}

/// A class which mocks [RemoveFavorite].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveFavorite extends _i1.Mock implements _i13.RemoveFavorite {
  MockRemoveFavorite() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.FavoritesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFavoritesRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.FavoritesRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, void>> call(String? symbol) =>
      (super.noSuchMethod(
            Invocation.method(#call, [symbol]),
            returnValue: _i6.Future<_i3.Either<_i7.Failure, void>>.value(
              _FakeEither_1<_i7.Failure, void>(
                this,
                Invocation.method(#call, [symbol]),
              ),
            ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, void>>);
}

/// A class which mocks [LocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorage extends _i1.Mock implements _i14.LocalStorage {
  MockLocalStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String?> getString(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int?> getInt(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getInt, [key]),
            returnValue: _i6.Future<int?>.value(),
          )
          as _i6.Future<int?>);

  @override
  _i6.Future<void> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool?> getBool(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key]),
            returnValue: _i6.Future<bool?>.value(),
          )
          as _i6.Future<bool?>);

  @override
  _i6.Future<void> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<double?> getDouble(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getDouble, [key]),
            returnValue: _i6.Future<double?>.value(),
          )
          as _i6.Future<double?>);

  @override
  _i6.Future<void> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<String>?> getStringList(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getStringList, [key]),
            returnValue: _i6.Future<List<String>?>.value(),
          )
          as _i6.Future<List<String>?>);

  @override
  _i6.Future<void> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>?> getJson(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getJson, [key]),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<void> setJson(String? key, Map<String, dynamic>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setJson, [key, value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}
